### ISSUE TITLE
gen_snapshot for aarch64

### ISSUE THREAD

**Issue by RossComputerGuy** [ardera/flutter-ci#14]
I'm trying to get the artifacts to work on aarch64 on an M1 Pro running NixOS Asahi, I've noticed there's only `gen_snapshot_linux_x64_*` but no `gen_snapshot_linux_aarch64_*`. Could the binary please be added in?

**Comment by ardera** [comment]
That's reasonable, but it could be it's not that easy; I need to look into how the flutter folks do it in their CI.

**Comment by ardera** [comment]
The MacOS binaries are there now (at least once CI runs through again). Only x64 for now, so you need to use Rosetta, but it works pretty well for that
